// Generated by gencpp from file super_lio/CloudPose2.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_CLOUDPOSE2_H
#define SUPER_LIO_MESSAGE_CLOUDPOSE2_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace super_lio
{
template <class ContainerAllocator>
struct CloudPose2_
{
  typedef CloudPose2_<ContainerAllocator> Type;

  CloudPose2_()
    : header()
    , pose()
    , cloud_lidar()  {
    }
  CloudPose2_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , cloud_lidar(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pose_type;
  _pose_type pose;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _cloud_lidar_type;
  _cloud_lidar_type cloud_lidar;





  typedef boost::shared_ptr< ::super_lio::CloudPose2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::CloudPose2_<ContainerAllocator> const> ConstPtr;

}; // struct CloudPose2_

typedef ::super_lio::CloudPose2_<std::allocator<void> > CloudPose2;

typedef boost::shared_ptr< ::super_lio::CloudPose2 > CloudPose2Ptr;
typedef boost::shared_ptr< ::super_lio::CloudPose2 const> CloudPose2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::CloudPose2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::CloudPose2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::CloudPose2_<ContainerAllocator1> & lhs, const ::super_lio::CloudPose2_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.cloud_lidar == rhs.cloud_lidar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::CloudPose2_<ContainerAllocator1> & lhs, const ::super_lio::CloudPose2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::CloudPose2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::CloudPose2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::CloudPose2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::CloudPose2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::CloudPose2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::CloudPose2_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::CloudPose2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8630ae852b0d52458b16663404acd015";
  }

  static const char* value(const ::super_lio::CloudPose2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8630ae852b0d5245ULL;
  static const uint64_t static_value2 = 0x8b16663404acd015ULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::CloudPose2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/CloudPose2";
  }

  static const char* value(const ::super_lio::CloudPose2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::CloudPose2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CloudPose2.msg\n"
"std_msgs/Header header\n"
"float32[] pose # [x y z | R00 R01 R02 | R10 R11 R12 | R20 R21 R22]\n"
"float32[] cloud_lidar   #  dense point cloud\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::super_lio::CloudPose2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::CloudPose2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.cloud_lidar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CloudPose2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::CloudPose2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::CloudPose2_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    if (v.pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.pose[i]);
    }
    if (v.pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cloud_lidar: ";
    if (v.cloud_lidar.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.cloud_lidar.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.cloud_lidar[i]);
    }
    if (v.cloud_lidar.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_CLOUDPOSE2_H
