// Generated by gencpp from file super_lio/GetMapResponse.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_GETMAPRESPONSE_H
#define SUPER_LIO_MESSAGE_GETMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace super_lio
{
template <class ContainerAllocator>
struct GetMapResponse_
{
  typedef GetMapResponse_<ContainerAllocator> Type;

  GetMapResponse_()
    : success(false)
    , map_data()  {
    }
  GetMapResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , map_data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _map_data_type;
  _map_data_type map_data;





  typedef boost::shared_ptr< ::super_lio::GetMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::GetMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapResponse_

typedef ::super_lio::GetMapResponse_<std::allocator<void> > GetMapResponse;

typedef boost::shared_ptr< ::super_lio::GetMapResponse > GetMapResponsePtr;
typedef boost::shared_ptr< ::super_lio::GetMapResponse const> GetMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::GetMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::GetMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::GetMapResponse_<ContainerAllocator1> & lhs, const ::super_lio::GetMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.map_data == rhs.map_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::GetMapResponse_<ContainerAllocator1> & lhs, const ::super_lio::GetMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::GetMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::GetMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::GetMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::GetMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::GetMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::GetMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::GetMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94dbb469f2f8ef9b17a6d045e2db96e8";
  }

  static const char* value(const ::super_lio::GetMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94dbb469f2f8ef9bULL;
  static const uint64_t static_value2 = 0x17a6d045e2db96e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::GetMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/GetMapResponse";
  }

  static const char* value(const ::super_lio::GetMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::GetMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float32[] map_data\n"
;
  }

  static const char* value(const ::super_lio::GetMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::GetMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.map_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::GetMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::GetMapResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_data: ";
    if (v.map_data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.map_data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.map_data[i]);
    }
    if (v.map_data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_GETMAPRESPONSE_H
