// Generated by gencpp from file super_lio/GetMapRequest.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_GETMAPREQUEST_H
#define SUPER_LIO_MESSAGE_GETMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace super_lio
{
template <class ContainerAllocator>
struct GetMapRequest_
{
  typedef GetMapRequest_<ContainerAllocator> Type;

  GetMapRequest_()
    : cmd_id(0)
    , enable_filter(false)
    , map_dir()
    , map_name()  {
    }
  GetMapRequest_(const ContainerAllocator& _alloc)
    : cmd_id(0)
    , enable_filter(false)
    , map_dir(_alloc)
    , map_name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_id_type;
  _cmd_id_type cmd_id;

   typedef uint8_t _enable_filter_type;
  _enable_filter_type enable_filter;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_dir_type;
  _map_dir_type map_dir;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_name_type;
  _map_name_type map_name;





  typedef boost::shared_ptr< ::super_lio::GetMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::GetMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapRequest_

typedef ::super_lio::GetMapRequest_<std::allocator<void> > GetMapRequest;

typedef boost::shared_ptr< ::super_lio::GetMapRequest > GetMapRequestPtr;
typedef boost::shared_ptr< ::super_lio::GetMapRequest const> GetMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::GetMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::GetMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::GetMapRequest_<ContainerAllocator1> & lhs, const ::super_lio::GetMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_id == rhs.cmd_id &&
    lhs.enable_filter == rhs.enable_filter &&
    lhs.map_dir == rhs.map_dir &&
    lhs.map_name == rhs.map_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::GetMapRequest_<ContainerAllocator1> & lhs, const ::super_lio::GetMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::GetMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::GetMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::GetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::GetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::GetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::GetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::GetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56d94d68084261c5f3cb6167efc096b6";
  }

  static const char* value(const ::super_lio::GetMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56d94d68084261c5ULL;
  static const uint64_t static_value2 = 0xf3cb6167efc096b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::GetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/GetMapRequest";
  }

  static const char* value(const ::super_lio::GetMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::GetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cmd_id\n"
"bool enable_filter\n"
"string map_dir\n"
"string map_name\n"
;
  }

  static const char* value(const ::super_lio::GetMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::GetMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_id);
      stream.next(m.enable_filter);
      stream.next(m.map_dir);
      stream.next(m.map_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::GetMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::GetMapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cmd_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable_filter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_filter);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_dir);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_GETMAPREQUEST_H
