// Generated by gencpp from file super_lio/GetMap.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_GETMAP_H
#define SUPER_LIO_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <super_lio/GetMapRequest.h>
#include <super_lio/GetMapResponse.h>


namespace super_lio
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace super_lio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::super_lio::GetMap > {
  static const char* value()
  {
    return "da421a37f6db773e999983c7c03e7333";
  }

  static const char* value(const ::super_lio::GetMap&) { return value(); }
};

template<>
struct DataType< ::super_lio::GetMap > {
  static const char* value()
  {
    return "super_lio/GetMap";
  }

  static const char* value(const ::super_lio::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::super_lio::GetMapRequest> should match
// service_traits::MD5Sum< ::super_lio::GetMap >
template<>
struct MD5Sum< ::super_lio::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::super_lio::GetMap >::value();
  }
  static const char* value(const ::super_lio::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::super_lio::GetMapRequest> should match
// service_traits::DataType< ::super_lio::GetMap >
template<>
struct DataType< ::super_lio::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::super_lio::GetMap >::value();
  }
  static const char* value(const ::super_lio::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::super_lio::GetMapResponse> should match
// service_traits::MD5Sum< ::super_lio::GetMap >
template<>
struct MD5Sum< ::super_lio::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::super_lio::GetMap >::value();
  }
  static const char* value(const ::super_lio::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::super_lio::GetMapResponse> should match
// service_traits::DataType< ::super_lio::GetMap >
template<>
struct DataType< ::super_lio::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::super_lio::GetMap >::value();
  }
  static const char* value(const ::super_lio::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPER_LIO_MESSAGE_GETMAP_H
