// Generated by gencpp from file super_lio/SetInitState.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_SETINITSTATE_H
#define SUPER_LIO_MESSAGE_SETINITSTATE_H

#include <ros/service_traits.h>


#include <super_lio/SetInitStateRequest.h>
#include <super_lio/SetInitStateResponse.h>


namespace super_lio
{

struct SetInitState
{

typedef SetInitStateRequest Request;
typedef SetInitStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitState
} // namespace super_lio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::super_lio::SetInitState > {
  static const char* value()
  {
    return "d3c9b48c351afea903277effa612f89c";
  }

  static const char* value(const ::super_lio::SetInitState&) { return value(); }
};

template<>
struct DataType< ::super_lio::SetInitState > {
  static const char* value()
  {
    return "super_lio/SetInitState";
  }

  static const char* value(const ::super_lio::SetInitState&) { return value(); }
};


// service_traits::MD5Sum< ::super_lio::SetInitStateRequest> should match
// service_traits::MD5Sum< ::super_lio::SetInitState >
template<>
struct MD5Sum< ::super_lio::SetInitStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::super_lio::SetInitState >::value();
  }
  static const char* value(const ::super_lio::SetInitStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::super_lio::SetInitStateRequest> should match
// service_traits::DataType< ::super_lio::SetInitState >
template<>
struct DataType< ::super_lio::SetInitStateRequest>
{
  static const char* value()
  {
    return DataType< ::super_lio::SetInitState >::value();
  }
  static const char* value(const ::super_lio::SetInitStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::super_lio::SetInitStateResponse> should match
// service_traits::MD5Sum< ::super_lio::SetInitState >
template<>
struct MD5Sum< ::super_lio::SetInitStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::super_lio::SetInitState >::value();
  }
  static const char* value(const ::super_lio::SetInitStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::super_lio::SetInitStateResponse> should match
// service_traits::DataType< ::super_lio::SetInitState >
template<>
struct DataType< ::super_lio::SetInitStateResponse>
{
  static const char* value()
  {
    return DataType< ::super_lio::SetInitState >::value();
  }
  static const char* value(const ::super_lio::SetInitStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPER_LIO_MESSAGE_SETINITSTATE_H
