// Generated by gencpp from file super_lio/SetInitStateResponse.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_SETINITSTATERESPONSE_H
#define SUPER_LIO_MESSAGE_SETINITSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace super_lio
{
template <class ContainerAllocator>
struct SetInitStateResponse_
{
  typedef SetInitStateResponse_<ContainerAllocator> Type;

  SetInitStateResponse_()
    : success(false)  {
    }
  SetInitStateResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::super_lio::SetInitStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::SetInitStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetInitStateResponse_

typedef ::super_lio::SetInitStateResponse_<std::allocator<void> > SetInitStateResponse;

typedef boost::shared_ptr< ::super_lio::SetInitStateResponse > SetInitStateResponsePtr;
typedef boost::shared_ptr< ::super_lio::SetInitStateResponse const> SetInitStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::SetInitStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::SetInitStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::SetInitStateResponse_<ContainerAllocator1> & lhs, const ::super_lio::SetInitStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::SetInitStateResponse_<ContainerAllocator1> & lhs, const ::super_lio::SetInitStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetInitStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetInitStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetInitStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::super_lio::SetInitStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/SetInitStateResponse";
  }

  static const char* value(const ::super_lio::SetInitStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::super_lio::SetInitStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInitStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::SetInitStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::SetInitStateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_SETINITSTATERESPONSE_H
