// Generated by gencpp from file super_lio/SetInitStateRequest.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_SETINITSTATEREQUEST_H
#define SUPER_LIO_MESSAGE_SETINITSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace super_lio
{
template <class ContainerAllocator>
struct SetInitStateRequest_
{
  typedef SetInitStateRequest_<ContainerAllocator> Type;

  SetInitStateRequest_()
    : cmd_id(0)
    , pose()
    , map_data()  {
    }
  SetInitStateRequest_(const ContainerAllocator& _alloc)
    : cmd_id(0)
    , pose(_alloc)
    , map_data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_id_type;
  _cmd_id_type cmd_id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pose_type;
  _pose_type pose;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _map_data_type;
  _map_data_type map_data;





  typedef boost::shared_ptr< ::super_lio::SetInitStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::SetInitStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInitStateRequest_

typedef ::super_lio::SetInitStateRequest_<std::allocator<void> > SetInitStateRequest;

typedef boost::shared_ptr< ::super_lio::SetInitStateRequest > SetInitStateRequestPtr;
typedef boost::shared_ptr< ::super_lio::SetInitStateRequest const> SetInitStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::SetInitStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::SetInitStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::SetInitStateRequest_<ContainerAllocator1> & lhs, const ::super_lio::SetInitStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_id == rhs.cmd_id &&
    lhs.pose == rhs.pose &&
    lhs.map_data == rhs.map_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::SetInitStateRequest_<ContainerAllocator1> & lhs, const ::super_lio::SetInitStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetInitStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetInitStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetInitStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8094dc94b71e634a58006d4568a7b3d";
  }

  static const char* value(const ::super_lio::SetInitStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8094dc94b71e634ULL;
  static const uint64_t static_value2 = 0xa58006d4568a7b3dULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/SetInitStateRequest";
  }

  static const char* value(const ::super_lio::SetInitStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cmd_id\n"
"float32[] pose\n"
"float32[] map_data\n"
;
  }

  static const char* value(const ::super_lio::SetInitStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_id);
      stream.next(m.pose);
      stream.next(m.map_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInitStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::SetInitStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::SetInitStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cmd_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    if (v.pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.pose[i]);
    }
    if (v.pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_data: ";
    if (v.map_data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.map_data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.map_data[i]);
    }
    if (v.map_data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_SETINITSTATEREQUEST_H
