// Generated by gencpp from file super_lio/SetMapResponse.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_SETMAPRESPONSE_H
#define SUPER_LIO_MESSAGE_SETMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace super_lio
{
template <class ContainerAllocator>
struct SetMapResponse_
{
  typedef SetMapResponse_<ContainerAllocator> Type;

  SetMapResponse_()
    : success(false)
    , message()
    , full_path()  {
    }
  SetMapResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , full_path(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _full_path_type;
  _full_path_type full_path;





  typedef boost::shared_ptr< ::super_lio::SetMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::SetMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetMapResponse_

typedef ::super_lio::SetMapResponse_<std::allocator<void> > SetMapResponse;

typedef boost::shared_ptr< ::super_lio::SetMapResponse > SetMapResponsePtr;
typedef boost::shared_ptr< ::super_lio::SetMapResponse const> SetMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::SetMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::SetMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::SetMapResponse_<ContainerAllocator1> & lhs, const ::super_lio::SetMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.full_path == rhs.full_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::SetMapResponse_<ContainerAllocator1> & lhs, const ::super_lio::SetMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::SetMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6761fb54c2136075a1eb18129227459c";
  }

  static const char* value(const ::super_lio::SetMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6761fb54c2136075ULL;
  static const uint64_t static_value2 = 0xa1eb18129227459cULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::SetMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/SetMapResponse";
  }

  static const char* value(const ::super_lio::SetMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::SetMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ===== 响应 =====\n"
"bool   success         # 设置是否成功\n"
"string message         # 失败原因 / 实际生效的完整路径\n"
"string full_path       # 服务端回显的最终路径，方便客户端核对\n"
;
  }

  static const char* value(const ::super_lio::SetMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::SetMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.full_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::SetMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::SetMapResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "full_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.full_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_SETMAPRESPONSE_H
