// Generated by gencpp from file super_lio/SetMap.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_SETMAP_H
#define SUPER_LIO_MESSAGE_SETMAP_H

#include <ros/service_traits.h>


#include <super_lio/SetMapRequest.h>
#include <super_lio/SetMapResponse.h>


namespace super_lio
{

struct SetMap
{

typedef SetMapRequest Request;
typedef SetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMap
} // namespace super_lio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::super_lio::SetMap > {
  static const char* value()
  {
    return "e8bb95334a41950ba2ca5ffc65897ce2";
  }

  static const char* value(const ::super_lio::SetMap&) { return value(); }
};

template<>
struct DataType< ::super_lio::SetMap > {
  static const char* value()
  {
    return "super_lio/SetMap";
  }

  static const char* value(const ::super_lio::SetMap&) { return value(); }
};


// service_traits::MD5Sum< ::super_lio::SetMapRequest> should match
// service_traits::MD5Sum< ::super_lio::SetMap >
template<>
struct MD5Sum< ::super_lio::SetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::super_lio::SetMap >::value();
  }
  static const char* value(const ::super_lio::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::super_lio::SetMapRequest> should match
// service_traits::DataType< ::super_lio::SetMap >
template<>
struct DataType< ::super_lio::SetMapRequest>
{
  static const char* value()
  {
    return DataType< ::super_lio::SetMap >::value();
  }
  static const char* value(const ::super_lio::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::super_lio::SetMapResponse> should match
// service_traits::MD5Sum< ::super_lio::SetMap >
template<>
struct MD5Sum< ::super_lio::SetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::super_lio::SetMap >::value();
  }
  static const char* value(const ::super_lio::SetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::super_lio::SetMapResponse> should match
// service_traits::DataType< ::super_lio::SetMap >
template<>
struct DataType< ::super_lio::SetMapResponse>
{
  static const char* value()
  {
    return DataType< ::super_lio::SetMap >::value();
  }
  static const char* value(const ::super_lio::SetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPER_LIO_MESSAGE_SETMAP_H
