// Generated by gencpp from file super_lio/SetMapRequest.msg
// DO NOT EDIT!


#ifndef SUPER_LIO_MESSAGE_SETMAPREQUEST_H
#define SUPER_LIO_MESSAGE_SETMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace super_lio
{
template <class ContainerAllocator>
struct SetMapRequest_
{
  typedef SetMapRequest_<ContainerAllocator> Type;

  SetMapRequest_()
    : map_path()
    , map_name()
    , create_dir(false)  {
    }
  SetMapRequest_(const ContainerAllocator& _alloc)
    : map_path(_alloc)
    , map_name(_alloc)
    , create_dir(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_path_type;
  _map_path_type map_path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_name_type;
  _map_name_type map_name;

   typedef uint8_t _create_dir_type;
  _create_dir_type create_dir;





  typedef boost::shared_ptr< ::super_lio::SetMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::super_lio::SetMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMapRequest_

typedef ::super_lio::SetMapRequest_<std::allocator<void> > SetMapRequest;

typedef boost::shared_ptr< ::super_lio::SetMapRequest > SetMapRequestPtr;
typedef boost::shared_ptr< ::super_lio::SetMapRequest const> SetMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::super_lio::SetMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::super_lio::SetMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::super_lio::SetMapRequest_<ContainerAllocator1> & lhs, const ::super_lio::SetMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_path == rhs.map_path &&
    lhs.map_name == rhs.map_name &&
    lhs.create_dir == rhs.create_dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::super_lio::SetMapRequest_<ContainerAllocator1> & lhs, const ::super_lio::SetMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace super_lio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::super_lio::SetMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::super_lio::SetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::super_lio::SetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::super_lio::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa36e297a10dc016654c614a5de292f1";
  }

  static const char* value(const ::super_lio::SetMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa36e297a10dc016ULL;
  static const uint64_t static_value2 = 0x654c614a5de292f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::super_lio::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "super_lio/SetMapRequest";
  }

  static const char* value(const ::super_lio::SetMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::super_lio::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ===== 请求 =====\n"
"string map_path        # 地图文件保存目录，如 /home/user/maps\n"
"string map_name        # 地图名，如 office_floor1（不带扩展名）\n"
"bool   create_dir      # 目录不存在时是否自动创建\n"
;
  }

  static const char* value(const ::super_lio::SetMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::super_lio::SetMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_path);
      stream.next(m.map_name);
      stream.next(m.create_dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::super_lio::SetMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::super_lio::SetMapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "map_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "create_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.create_dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPER_LIO_MESSAGE_SETMAPREQUEST_H
